# Generated by Django 5.1.4 on 2024-12-07 22:17

from django.db import migrations

def populate_status(apps, schemaeditor):
    entries = {
        "to do": "An issue for which work has not yet started",
        "in progress": "An issue actively being worked on",
        "done": "An issue for which work has been completed"
    }
    Status = apps.get_model("issues", "Status")
    for key, value in entries.items():
        status = Status(name=key, description=value)
        status.save()

class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_status)       # don't forget this!
    ]
